 using System;
using System.Collections.Generic;
using System.Text;

namespace EMS.DbModelRepository.Models
{
    public class EmsMaster : BaseModel
    {
        public int DeviceId { get; set; }
        public DateTime DateEms { get; set; }
        public int StartingAddress { get; set; }
        public int SlaveId { get; set; }
        public int FunctionCode { get; set; }
        public int DataPort { get; set; }
        public float VLLAVG { get; set; }
        public float VRY { get; set; }
        public float VYB { get; set; }
        public float VBR { get; set; }
        public float VLNAVG { get; set; }
        public float VR { get; set; }
        public float VY { get; set; }
        public float VB { get; set; }
        public float IAVG { get; set; }
        public float IR { get; set; }
        public float IY { get; set; }
        public float IB { get; set; }
        public float HZ { get; set; }
        public float PFAVG { get; set; }
        public float PFR { get; set; }
        public float PFY { get; set; }
        public float PFB { get; set; }
        public float WattsTot { get; set; }
        public float WR { get; set; }
        public float WY { get; set; }
        public float WB { get; set; }
        public float VATOT { get; set; }
        public float VAR { get; set; }
        public float VAY { get; set; }
        public float VAB { get; set; }
        public float VARTOT { get; set; }
        public float VARR { get; set; }
        public float VARY { get; set; }
        public float VARB { get; set; }
        public float WHCONTOT { get; set; }
        public float WHCR { get; set; }
        public float WHCY { get; set; }
        public float WHCB { get; set; }
        public float WHGENTOT { get; set; }
        public float WHGR { get; set; }
        public float WHGY { get; set; }
        public float WHGB { get; set; }
        public float VAHCONTOT { get; set; }
        public float VAHCR { get; set; }
        public float VAHCY { get; set; }
        public float VAHCB { get; set; }
        public float VAHGENTOT { get; set; }
        public float VAHGR { get; set; }
        public float VAHGY { get; set; }
        public float VAHGB { get; set; }
        public float VARHTOT { get; set; }
        public float VARHR { get; set; }
        public float VARHY { get; set; }
        public float VARHB { get; set; }
        public float VARHCAPT { get; set; }
        public float VARHCAPR { get; set; }
        public float VARHCAPY { get; set; }
        public float VARHCAPB { get; set; }
        public float VARHINDT { get; set; }
        public float VARHINDR { get; set; }
        public float VARHINDY { get; set; }
        public float VARHINDB { get; set; }
        public float RPM { get; set; }
        public float UNBALANCEVOLTAGEVLL { get; set; }
        public float UNBALANCEVOLTAGEVLN { get; set; }
        public float UNBALANCECURRENTAMPS { get; set; }
        public float NEUTRALCURRENTLN { get; set; }
        public float MAXIMAMDEMAND { get; set; }
        public float RISINGDEMAND { get; set; }
        public float DEMAND1 { get; set; }
        public float DEMAND2 { get; set; }
        public float DEMAND3 { get; set; }
        public float THDVOLTAGEVLL { get; set; }
        public float THDVOLTAGEVLN { get; set; }
        public float THDCURRENTA { get; set; }
        public float FIRSTSTHRVRY { get; set; }
        public float FIRSTSTHRVYB { get; set; }
        public float FIRSTSTHRVBR { get; set; }
        public float FIRSTSTHRIR { get; set; }
        public float FIRSTSTHRIY { get; set; }
        public float FIRSTSTHRIB { get; set; }
        public float SECONDHARVRY { get; set; }
        public float SECONDHARVYB { get; set; }
        public float SECONDHARVBR { get; set; }
        public float SECONDHARIR { get; set; }
        public float SECONDHARIY { get; set; }
        public float SECONDHARIB { get; set; }

        public float THIRDHARVRY { get; set; }
        public float THIRDHARVYB { get; set; }
        public float THIRDHARVBR { get; set; }
        public float THIRDHARIR { get; set; }
        public float THIRDHARIY { get; set; }
        public float THIRDHARIB { get; set; }

        public float FOURTHHARVRY { get; set; }
        public float FOURTHARVYB { get; set; }
        public float THIRDDHARVBR { get; set; }
        public float FOURTHHARIR { get; set; }
        public float FOURTHHARIY { get; set; }
        public float FOURTHHARIB { get; set; }
        public float FIFTHHARVRY { get; set; }
        public float FIFTHHARVYB { get; set; }
        public float FIFTHHARVBR { get; set; }
        public float FIFTHHARIR { get; set; }
        public float FIFTHHARIY { get; set; }
        public float FIFTHHARIB { get; set; }
        public float SIXTHHARVRY { get; set; }
        public float SIXTHHARVYB { get; set; }
        public float SIXTHHARVBR { get; set; }
        public float SIXTHHARIR { get; set; }
        public float SIXTHHARIY { get; set; }
        public float SIXTHHARIB { get; set; }

        public float SEVENTHHARVRY { get; set; }
        public float SEVENTHHARVYB { get; set; }
        public float SEVENTHHARVBR { get; set; }
        public float SEVENTHHARIR { get; set; }
        public float SEVENTHHARIY { get; set; }
        public float SEVENTHHARIB { get; set; }

        public float EIGHTHARVRY { get; set; }
        public float EIGHTHARVYB { get; set; }
        public float EIGHTHARVBR { get; set; }
        public float EIGHTHARIR { get; set; }
        public float EIGHTHARIY { get; set; }
        public float EIGHTHARIB { get; set; }

        public float NINTHHARVRY { get; set; }
        public float NINTHHARVYB { get; set; }
        public float NINTHHARVBR { get; set; }
        public float NINTHHARIR { get; set; }
        public float NINTHHARIY { get; set; }
        public float NINTHHARIB { get; set; }

        public float TENTHHARVRY { get; set; }
        public float TENTHHARVYB { get; set; }
        public float TENTHHARVBR { get; set; }
        public float TENTHHARIR { get; set; }
        public float TENTHHARIY { get; set; }
        public float TENTHHARIB { get; set; }

        public float ELEVENTHHARVRY { get; set; }
        public float ELEVENTHHARVYB { get; set; }
        public float ELEVENTHHARVBR { get; set; }
        public float ELEVENTHHARIR { get; set; }
        public float ELEVENTHHARIY { get; set; }
        public float ELEVENTHHARIB { get; set; }

        public float TWELVEHARVRY { get; set; }
        public float TWELVEHARVYB { get; set; }
        public float TWELVEHARVBR { get; set; }
        public float TWELVEHARIR { get; set; }
        public float TWELVEHARIY { get; set; }
        public float TWELVEHARIB { get; set; }

        public float THIRTEENHARVRY { get; set; }
        public float THIRTEENHARVYB { get; set; }
        public float THIRTEENHARVBR { get; set; }
        public float THIRTEENHARIR { get; set; }
        public float THIRTEENHARIY { get; set; }
        public float THIRTEENHARIB { get; set; }

        public float FOURTEENHARVRY { get; set; }
        public float FOURTEENHARVYB { get; set; }
        public float FOURTEENHARVBR { get; set; }
        public float FOURTEENHARIR { get; set; }
        public float FOURTEENHARIY { get; set; }
        public float FOURTEENHARIB { get; set; }

        public float FIFTHEENHARVRY { get; set; }
        public float FIFTHEENHARVYB { get; set; }
        public float FIFTHEENHARVBR { get; set; }
        public float FIFTHEENHARIR { get; set; }
        public float FIFTHEENHARIY { get; set; }
        public float FIFTHEENHARIB { get; set; }

        public float SIXTHEENHARVRY { get; set; }
        public float SIXTHEENHARVYB { get; set; }
        public float SIXTHEENHARVBR { get; set; }
        public float SIXTHEENHARIR { get; set; }
        public float SIXTHEENHARIY { get; set; }
        public float SIXTHEENHARIB { get; set; }

        public float SEVENTHEENHARVRY { get; set; }
        public float SEVENTHEENHARVYB { get; set; }
        public float SEVENTHEENHARVBR { get; set; }
        public float SEVENTHEENHARIR { get; set; }
        public float SEVENTHEENHARIY { get; set; }
        public float SEVENTHEENHARIB { get; set; }

        public float EIGHTHEENHARVRY { get; set; }
        public float EIGHTHEENHARVYB { get; set; }
        public float EIGHTHEENHARVBR { get; set; }
        public float EIGHTHEENHARIR { get; set; }
        public float EIGHTHEENHARIY { get; set; }
        public float EIGHTEENHARIB { get; set; }

        public float NINTHEENHARVRY { get; set; }
        public float NINTHEENHARVYB { get; set; }
        public float NINTHEENHARVBR { get; set; }
        public float NINTHEENHARIR { get; set; }
        public float NINTHEENHARIY { get; set; }
        public float NINTHEENHARIB { get; set; }

        public float TWENTYHARVRY { get; set; }
        public float TWENTYHARVYB { get; set; }
        public float TWENTYHARVBR { get; set; }
        public float TWENTYHARIR { get; set; }
        public float TWENTYHARIY { get; set; }
        public float TWENTYHARIB { get; set; }

        public float TWENTY1HARVRY { get; set; }
        public float TWENTY1HARVYB { get; set; }
        public float TWENTY1HARVBR { get; set; }
        public float TWENTY1HARIR { get; set; }
        public float TWENTY1HARIY { get; set; }
        public float TWENTY1HARIB { get; set; }

        public float TWENTY2HARVRY { get; set; }
        public float TWENTY2HARVYB { get; set; }
        public float TWENTY2HARVBR { get; set; }
        public float TWENTY2HARIR { get; set; }
        public float TWENTY2HARIY { get; set; }
        public float TWENTY2HARIB { get; set; }

        public float TWENTY3HARVRY { get; set; }
        public float TWENTY3HARVYB { get; set; }
        public float TWENTY3HARVBR { get; set; }
        public float TWENTY3HARIR { get; set; }
        public float TWENTY3HARIY { get; set; }
        public float TWENTY3HARIB { get; set; }

        public float TWENTY4HARVRY { get; set; }
        public float TWENTY4HARVYB { get; set; }
        public float TWENTY4HARVBR { get; set; }
        public float TWENTY4HARIR { get; set; }
        public float TWENTY4HARIY { get; set; }
        public float TWENTY4HARIB { get; set; }

        public float TWENTY5HARVRY { get; set; }
        public float TWENTY5HARVYB { get; set; }
        public float TWENTY5HARVBR { get; set; }
        public float TWENTY5HARIR { get; set; }
        public float TWENTY5HARIY { get; set; }
        public float TWENTY5HARIB { get; set; }

        public float TWENTY6HARVRY { get; set; }
        public float TWENTY6HARVYB { get; set; }
        public float TWENTY6HARVBR { get; set; }
        public float TWENTY6HARIR { get; set; }
        public float TWENTY6HARIY { get; set; }
        public float TWENTY6HARIB { get; set; }

        public float TWENTY7HARVRY { get; set; }
        public float TWENTY7HARVYB { get; set; }
        public float TWENTY7HARVBR { get; set; }
        public float TWENTY7HARIR { get; set; }
        public float TWENTY7HARIY { get; set; }
        public float TWENTY7HARIB { get; set; }

        public float TWENTY8HARVRY { get; set; }
        public float TWENTY8HARVYB { get; set; }
        public float TWENTY8HARVBR { get; set; }
        public float TWENTY8HARIR { get; set; }
        public float TWENTY8HARIY { get; set; }
        public float TWENTY8HARIB { get; set; }

        public float TWENTY9HARVRY { get; set; }
        public float TWENTY9HARVYB { get; set; }
        public float TWENTY9HARVBR { get; set; }
        public float TWENTY9HARIR { get; set; }
        public float TWENTY9HARIY { get; set; }
        public float TWENTY9HARIB { get; set; }

        public float THIRTYHARVRY { get; set; }
        public float THIRTYHARVYB { get; set; }
        public float THIRTYHARVBR { get; set; }
        public float THIRTYHARIR { get; set; }
        public float THIRTYHARIY { get; set; }
        public float THIRTYHARIB { get; set; }
        public float THIRTY1HARVRY { get; set; }
        public float THIRTY1HARVYB { get; set; }
        public float THIRTY1HARVBR { get; set; }
        public float THIRTY1HARIR { get; set; }
        public float THIRTY1HARIY { get; set; }
        public float THIRTY1HARIB { get; set; }

        public float THIRTY2HARVRY { get; set; }
        public float THIRTY2HARVYB { get; set; }
        public float THIRTY2HARVBR { get; set; }
        public float THIRTY2HARIR { get; set; }
        public float THIRTY2HARIY { get; set; }
        public float THIRTY2HARIB { get; set; }

        public float THIRTY3HARVRY { get; set; }
        public float THIRTY3HARVYB { get; set; }
        public float THIRTY3HARVBR { get; set; }
        public float THIRTY3HARIR { get; set; }
        public float THIRTY3HARIY { get; set; }
        public float THIRTY3HARIB { get; set; }

        public float ANALOGINPUT1 { get; set; }
        public float ANALOGINPUT2 { get; set; }
        public float ANALOGINPUT21 { get; set; }
        public float ANALOGINPUT3 { get; set; }
        public float ANALOGINPUT31 { get; set; }
        public float ANALOGINPUT4 { get; set; }
        public float ANALOGINPUT41 { get; set; }
        public float ANALOGINPUT5 { get; set; }
        public float ANALOGINPUT51 { get; set; }
        public float ANALOGINPUT6 { get; set; }
        public float ANALOGINPUT61 { get; set; }
        public float ANALOGINPUT7 { get; set; }
        public float ANALOGINPUT71 { get; set; }
        public float ANALOGINPUT8 { get; set; }
        public float ANALOGINPUT81 { get; set; }
        public float ANALOGINPUT9 { get; set; }
        public float ANALOGINPUT91 { get; set; }
        public float ANALOGINPUT10 { get; set; }
        public float ANALOGINPUT101 { get; set; }
        public float ANALOGINPUT11 { get; set; }
        public float ANALOGINPUT111 { get; set; }
        public float ANALOGINPUT12 { get; set; }

        public float DIGITALINPUT1 { get; set; }
        public float DIGITALINPUT2 { get; set; }
        public float DIGITALINPUT21 { get; set; }
        public float DIGITALINPUT3 { get; set; }
        public float DIGITALINPUT31 { get; set; }
        public float DIGITALINPUT4 { get; set; }
        public float DIGITALINPUT41 { get; set; }
        public float DIGITALINPUT5 { get; set; }
        public float DIGITALINPUT51 { get; set; }
        public float DIGITALINPUT6 { get; set; }
        public float DIGITALINPUT61 { get; set; }
        public float DIGITALINPUT7 { get; set; }
        public float DIGITALINPUT71 { get; set; }
        public float DIGITALINPUT8 { get; set; }
        public float DIGITALINPUT81 { get; set; }
        public float DIGITALINPUT9 { get; set; }
        public float DIGITALINPUT91 { get; set; }
        public float DIGITALINPUT10 { get; set; }
        public float DIGITALINPUT101 { get; set; }
        public float DIGITALINPUT11 { get; set; }
        public float DIGITALINPUT111 { get; set; }
        public float DIGITALINPUT12 { get; set; }

        public float DIGITALOUTPUT1 { get; set; }
        public float DIGITALOUTPUT2 { get; set; }
        public float DIGITALOUTPUT21 { get; set; }
        public float DIGITALOUTPUT3 { get; set; }
        public float DIGITALOUTPUT31 { get; set; }
        public float DIGITALOUTPUT4 { get; set; }
        public float DIGITALOUTPUT41 { get; set; }
        public float DIGITALOUTPUT5 { get; set; }
        public float DIGITALOUTPUT51 { get; set; }
        public float DIGITALOUTPUT6 { get; set; }
        public float DIGITALOUTPUT61 { get; set; }
        public float DIGITALOUTPUT7 { get; set; }
        public float DIGITALOUTPUT71 { get; set; }
        public float DIGITALOUTPUT8 { get; set; }
        public float DIGITALOUTPUT81 { get; set; }
        public float DIGITALOUTPUT9 { get; set; }
        public float DIGITALOUTPUT91 { get; set; }
        public float DIGITALOUTPUT10 { get; set; }
        public float DIGITALOUTPUT101 { get; set; }
        public float DIGITALOUTPUT11 { get; set; }
        public float DIGITALOUTPUT111 { get; set; }
        public float DIGITALOUTPUT12 { get; set; }

        public float PULSEOUTPUT1 { get; set; }
        public float PULSEOUTPUT2 { get; set; }
        public float PULSEOUTPUT3 { get; set; }
        public float PULSEOUTPUT4 { get; set; }
        public float PULSEOUTPUT5 { get; set; }
        public float PULSEOUTPUT6 { get; set; }

        public float ABTBLOCK1 { get; set; }
        public float ABTBLOCK2 { get; set; }
        public float ABTBLOCK3 { get; set; }
        public float ABTBLOCK4 { get; set; }
        public float ABTBLOCK5 { get; set; }
        public float ABTBLOCK6 { get; set; }
        public float ABTBLOCK7 { get; set; }
        public float ABTBLOCK8 { get; set; }
        public float ABTBLOCK9 { get; set; }
        public float ABTBLOCK10 { get; set; }
        public float ABTBLOCK11 { get; set; }
        public float ABTBLOCK12 { get; set; }
        public float ABTBLOCK13 { get; set; }
        public float ABTBLOCK14 { get; set; }
        public float ABTBLOCK15 { get; set; }
        public float ABTBLOCK16 { get; set; }
        public float ABTBLOCK17 { get; set; }
        public float ABTBLOCK18 { get; set; }
        public float ABTBLOCK19 { get; set; }
        public float ABTBLOCK20 { get; set; }
        public float ABTBLOCK21 { get; set; }
        public float ABTBLOCK22 { get; set; }
        public float ABTBLOCK23 { get; set; }
        public float ABTBLOCK24 { get; set; }
        public float ABTBLOCK25 { get; set; }
        public float ABTBLOCK26 { get; set; }
        public float ABTBLOCK27 { get; set; }
        public float ABTBLOCK28 { get; set; }
        public float ABTBLOCK29 { get; set; }
        public float ABTBLOCK30 { get; set; }
        public float ABTBLOCK31 { get; set; }
        public float ABTBLOCK32 { get; set; }
        public float ABTBLOCK33 { get; set; }
        public float ABTBLOCK34 { get; set; }
        public float ABTBLOCK35 { get; set; }
        public float ABTBLOCK36 { get; set; }
        public float ABTBLOCK37 { get; set; }
        public float ABTBLOCK38 { get; set; }
        public float ABTBLOCK39 { get; set; }
        public float ABTBLOCK40 { get; set; }
        public float ABTBLOCK41 { get; set; }
        public float ABTBLOCK42 { get; set; }
        public float ABTBLOCK43 { get; set; }
        public float ABTBLOCK44 { get; set; }
        public float ABTBLOCK45 { get; set; }
        public float ABTBLOCK46 { get; set; }
        public float ABTBLOCK47 { get; set; }
        public float ABTBLOCK48 { get; set; }
        public float ABTBLOCK49 { get; set; }
        public float ABTBLOCK50 { get; set; }
        public float ABTBLOCK51 { get; set; }
        public float ABTBLOCK52 { get; set; }
        public float ABTBLOCK53 { get; set; }
        public float ABTBLOCK54 { get; set; }
        public float ABTBLOCK55 { get; set; }
        public float ABTBLOCK56 { get; set; }
        public float ABTBLOCK57 { get; set; }
        public float ABTBLOCK58 { get; set; }
        public float ABTBLOCK59 { get; set; }
        public float ABTBLOCK60 { get; set; }
        public float ABTBLOCK61 { get; set; }
        public float ABTBLOCK62 { get; set; }
        public float ABTBLOCK63 { get; set; }
        public float ABTBLOCK64 { get; set; }
        public float ABTBLOCK65 { get; set; }
        public float ABTBLOCK66 { get; set; }
        public float ABTBLOCK67 { get; set; }
        public float ABTBLOCK68 { get; set; }
        public float ABTBLOCK69 { get; set; }
        public float ABTBLOCK70 { get; set; }
        public float ABTBLOCK71 { get; set; }
        public float ABTBLOCK72 { get; set; }
        public float ABTBLOCK73 { get; set; }
        public float ABTBLOCK74 { get; set; }
        public float ABTBLOCK75 { get; set; }
        public float ABTBLOCK76 { get; set; }
        public float ABTBLOCK77 { get; set; }
        public float ABTBLOCK78 { get; set; }
        public float ABTBLOCK79 { get; set; }
        public float ABTBLOCK80 { get; set; }
        public float ABTBLOCK81 { get; set; }
        public float ABTBLOCK82 { get; set; }
        public float ABTBLOCK83 { get; set; }
        public float ABTBLOCK84 { get; set; }
        public float ABTBLOCK85 { get; set; }
        public float ABTBLOCK86 { get; set; }
        public float ABTBLOCK87 { get; set; }
        public float ABTBLOCK88 { get; set; }
        public float ABTBLOCK89 { get; set; }
        public float ABTBLOCK90 { get; set; }
        public float ABTBLOCK91 { get; set; }
        public float ABTBLOCK92 { get; set; }
        public float ABTBLOCK93 { get; set; }
        public float ABTBLOCK94 { get; set; }
        public float ABTBLOCK95 { get; set; }
        public float ABTBLOCK96 { get; set; }
    }
}
