using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EMS.ModelBuilderRepository.Migrations
{
    public partial class Add_Entire_Table : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "customers",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    StartDate = table.Column<DateTime>(nullable: false),
                    EndDate = table.Column<DateTime>(nullable: false),
                    CustomerName = table.Column<string>(nullable: true),
                    UserName = table.Column<string>(nullable: true),
                    UserPassword = table.Column<string>(nullable: true),
                    NoOfPlants = table.Column<int>(nullable: false),
                    PlantAddress = table.Column<string>(nullable: true),
                    ContactPerson = table.Column<string>(nullable: true),
                    Email = table.Column<string>(nullable: true),
                    MobilePhone = table.Column<string>(nullable: true),
                    Telephone = table.Column<string>(nullable: true),
                    Fax = table.Column<string>(nullable: true),
                    SocialMedia = table.Column<string>(nullable: true),
                    HeadOffice = table.Column<string>(nullable: true),
                    ContatctPerson = table.Column<string>(nullable: true),
                    WebSite = table.Column<string>(nullable: true),
                    GSTNumber = table.Column<string>(nullable: true),
                    PAN = table.Column<string>(nullable: true),
                    RRNumber = table.Column<string>(nullable: true),
                    TAN = table.Column<string>(nullable: true),
                    CIN = table.Column<string>(nullable: true),
                    UAM = table.Column<string>(nullable: true),
                    Activity = table.Column<string>(nullable: true),
                    Incomers = table.Column<int>(nullable: false),
                    DG = table.Column<int>(nullable: false),
                    Solar = table.Column<int>(nullable: false),
                    Demand = table.Column<int>(nullable: false),
                    DemandCharges = table.Column<int>(nullable: false),
                    PenaltyCharges = table.Column<int>(nullable: false),
                    NoOfTransformers = table.Column<int>(nullable: false),
                    Transformer1Rating = table.Column<int>(nullable: false),
                    Transformer2Rating = table.Column<int>(nullable: false),
                    Transformer3Rating = table.Column<int>(nullable: false),
                    Transformer4Rating = table.Column<int>(nullable: false),
                    Transformer5Rating = table.Column<int>(nullable: false),
                    NoOfMachine = table.Column<int>(nullable: false),
                    Unit = table.Column<int>(nullable: false),
                    LicenceExpiry = table.Column<DateTime>(nullable: false),
                    Monitoring = table.Column<bool>(nullable: false),
                    Controlling = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_customers", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "emsMaster",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    StartDate = table.Column<DateTime>(nullable: false),
                    EndDate = table.Column<DateTime>(nullable: false),
                    DeviceId = table.Column<int>(nullable: false),
                    DateEms = table.Column<DateTime>(nullable: false),
                    StartingAddress = table.Column<int>(nullable: false),
                    SlaveId = table.Column<int>(nullable: false),
                    FunctionCode = table.Column<int>(nullable: false),
                    DataPort = table.Column<int>(nullable: false),
                    VLLAVG = table.Column<float>(nullable: false),
                    VRY = table.Column<float>(nullable: false),
                    VYB = table.Column<float>(nullable: false),
                    VBR = table.Column<float>(nullable: false),
                    VLNAVG = table.Column<float>(nullable: false),
                    VR = table.Column<float>(nullable: false),
                    VY = table.Column<float>(nullable: false),
                    VB = table.Column<float>(nullable: false),
                    IAVG = table.Column<float>(nullable: false),
                    IR = table.Column<float>(nullable: false),
                    IY = table.Column<float>(nullable: false),
                    IB = table.Column<float>(nullable: false),
                    HZ = table.Column<float>(nullable: false),
                    PFAVG = table.Column<float>(nullable: false),
                    PFR = table.Column<float>(nullable: false),
                    PFY = table.Column<float>(nullable: false),
                    PFB = table.Column<float>(nullable: false),
                    WattsTot = table.Column<float>(nullable: false),
                    WR = table.Column<float>(nullable: false),
                    WY = table.Column<float>(nullable: false),
                    WB = table.Column<float>(nullable: false),
                    VATOT = table.Column<float>(nullable: false),
                    VAR = table.Column<float>(nullable: false),
                    VAY = table.Column<float>(nullable: false),
                    VAB = table.Column<float>(nullable: false),
                    VARTOT = table.Column<float>(nullable: false),
                    VARR = table.Column<float>(nullable: false),
                    VARY = table.Column<float>(nullable: false),
                    VARB = table.Column<float>(nullable: false),
                    WHCONTOT = table.Column<float>(nullable: false),
                    WHCR = table.Column<float>(nullable: false),
                    WHCY = table.Column<float>(nullable: false),
                    WHCB = table.Column<float>(nullable: false),
                    WHGENTOT = table.Column<float>(nullable: false),
                    WHGR = table.Column<float>(nullable: false),
                    WHGY = table.Column<float>(nullable: false),
                    WHGB = table.Column<float>(nullable: false),
                    VAHCONTOT = table.Column<float>(nullable: false),
                    VAHCR = table.Column<float>(nullable: false),
                    VAHCY = table.Column<float>(nullable: false),
                    VAHCB = table.Column<float>(nullable: false),
                    VAHGENTOT = table.Column<float>(nullable: false),
                    VAHGR = table.Column<float>(nullable: false),
                    VAHGY = table.Column<float>(nullable: false),
                    VAHGB = table.Column<float>(nullable: false),
                    VARHTOT = table.Column<float>(nullable: false),
                    VARHR = table.Column<float>(nullable: false),
                    VARHY = table.Column<float>(nullable: false),
                    VARHB = table.Column<float>(nullable: false),
                    VARHCAPT = table.Column<float>(nullable: false),
                    VARHCAPR = table.Column<float>(nullable: false),
                    VARHCAPY = table.Column<float>(nullable: false),
                    VARHCAPB = table.Column<float>(nullable: false),
                    VARHINDT = table.Column<float>(nullable: false),
                    VARHINDR = table.Column<float>(nullable: false),
                    VARHINDY = table.Column<float>(nullable: false),
                    VARHINDB = table.Column<float>(nullable: false),
                    RPM = table.Column<float>(nullable: false),
                    UNBALANCEVOLTAGEVLL = table.Column<float>(nullable: false),
                    UNBALANCEVOLTAGEVLN = table.Column<float>(nullable: false),
                    UNBALANCECURRENTAMPS = table.Column<float>(nullable: false),
                    NEUTRALCURRENTLN = table.Column<float>(nullable: false),
                    MAXIMAMDEMAND = table.Column<float>(nullable: false),
                    RISINGDEMAND = table.Column<float>(nullable: false),
                    DEMAND1 = table.Column<float>(nullable: false),
                    DEMAND2 = table.Column<float>(nullable: false),
                    DEMAND3 = table.Column<float>(nullable: false),
                    THDVOLTAGEVLL = table.Column<float>(nullable: false),
                    THDVOLTAGEVLN = table.Column<float>(nullable: false),
                    THDCURRENTA = table.Column<float>(nullable: false),
                    FIRSTSTHRVRY = table.Column<float>(nullable: false),
                    FIRSTSTHRVYB = table.Column<float>(nullable: false),
                    FIRSTSTHRVBR = table.Column<float>(nullable: false),
                    FIRSTSTHRIR = table.Column<float>(nullable: false),
                    FIRSTSTHRIY = table.Column<float>(nullable: false),
                    FIRSTSTHRIB = table.Column<float>(nullable: false),
                    SECONDHARVRY = table.Column<float>(nullable: false),
                    SECONDHARVYB = table.Column<float>(nullable: false),
                    SECONDHARVBR = table.Column<float>(nullable: false),
                    SECONDHARIR = table.Column<float>(nullable: false),
                    SECONDHARIY = table.Column<float>(nullable: false),
                    SECONDHARIB = table.Column<float>(nullable: false),
                    THIRDHARVRY = table.Column<float>(nullable: false),
                    THIRDHARVYB = table.Column<float>(nullable: false),
                    THIRDHARVBR = table.Column<float>(nullable: false),
                    THIRDHARIR = table.Column<float>(nullable: false),
                    THIRDHARIY = table.Column<float>(nullable: false),
                    THIRDHARIB = table.Column<float>(nullable: false),
                    FOURTHHARVRY = table.Column<float>(nullable: false),
                    FOURTHARVYB = table.Column<float>(nullable: false),
                    THIRDDHARVBR = table.Column<float>(nullable: false),
                    FOURTHHARIR = table.Column<float>(nullable: false),
                    FOURTHHARIY = table.Column<float>(nullable: false),
                    FOURTHHARIB = table.Column<float>(nullable: false),
                    FIFTHHARVRY = table.Column<float>(nullable: false),
                    FIFTHHARVYB = table.Column<float>(nullable: false),
                    FIFTHHARVBR = table.Column<float>(nullable: false),
                    FIFTHHARIR = table.Column<float>(nullable: false),
                    FIFTHHARIY = table.Column<float>(nullable: false),
                    FIFTHHARIB = table.Column<float>(nullable: false),
                    SIXTHHARVRY = table.Column<float>(nullable: false),
                    SIXTHHARVYB = table.Column<float>(nullable: false),
                    SIXTHHARVBR = table.Column<float>(nullable: false),
                    SIXTHHARIR = table.Column<float>(nullable: false),
                    SIXTHHARIY = table.Column<float>(nullable: false),
                    SIXTHHARIB = table.Column<float>(nullable: false),
                    SEVENTHHARVRY = table.Column<float>(nullable: false),
                    SEVENTHHARVYB = table.Column<float>(nullable: false),
                    SEVENTHHARVBR = table.Column<float>(nullable: false),
                    SEVENTHHARIR = table.Column<float>(nullable: false),
                    SEVENTHHARIY = table.Column<float>(nullable: false),
                    SEVENTHHARIB = table.Column<float>(nullable: false),
                    EIGHTHARVRY = table.Column<float>(nullable: false),
                    EIGHTHARVYB = table.Column<float>(nullable: false),
                    EIGHTHARVBR = table.Column<float>(nullable: false),
                    EIGHTHARIR = table.Column<float>(nullable: false),
                    EIGHTHARIY = table.Column<float>(nullable: false),
                    EIGHTHARIB = table.Column<float>(nullable: false),
                    NINTHHARVRY = table.Column<float>(nullable: false),
                    NINTHHARVYB = table.Column<float>(nullable: false),
                    NINTHHARVBR = table.Column<float>(nullable: false),
                    NINTHHARIR = table.Column<float>(nullable: false),
                    NINTHHARIY = table.Column<float>(nullable: false),
                    NINTHHARIB = table.Column<float>(nullable: false),
                    TENTHHARVRY = table.Column<float>(nullable: false),
                    TENTHHARVYB = table.Column<float>(nullable: false),
                    TENTHHARVBR = table.Column<float>(nullable: false),
                    TENTHHARIR = table.Column<float>(nullable: false),
                    TENTHHARIY = table.Column<float>(nullable: false),
                    TENTHHARIB = table.Column<float>(nullable: false),
                    ELEVENTHHARVRY = table.Column<float>(nullable: false),
                    ELEVENTHHARVYB = table.Column<float>(nullable: false),
                    ELEVENTHHARVBR = table.Column<float>(nullable: false),
                    ELEVENTHHARIR = table.Column<float>(nullable: false),
                    ELEVENTHHARIY = table.Column<float>(nullable: false),
                    ELEVENTHHARIB = table.Column<float>(nullable: false),
                    TWELVEHARVRY = table.Column<float>(nullable: false),
                    TWELVEHARVYB = table.Column<float>(nullable: false),
                    TWELVEHARVBR = table.Column<float>(nullable: false),
                    TWELVEHARIR = table.Column<float>(nullable: false),
                    TWELVEHARIY = table.Column<float>(nullable: false),
                    TWELVEHARIB = table.Column<float>(nullable: false),
                    THIRTEENHARVRY = table.Column<float>(nullable: false),
                    THIRTEENHARVYB = table.Column<float>(nullable: false),
                    THIRTEENHARVBR = table.Column<float>(nullable: false),
                    THIRTEENHARIR = table.Column<float>(nullable: false),
                    THIRTEENHARIY = table.Column<float>(nullable: false),
                    THIRTEENHARIB = table.Column<float>(nullable: false),
                    FOURTEENHARVRY = table.Column<float>(nullable: false),
                    FOURTEENHARVYB = table.Column<float>(nullable: false),
                    FOURTEENHARVBR = table.Column<float>(nullable: false),
                    FOURTEENHARIR = table.Column<float>(nullable: false),
                    FOURTEENHARIY = table.Column<float>(nullable: false),
                    FOURTEENHARIB = table.Column<float>(nullable: false),
                    FIFTHEENHARVRY = table.Column<float>(nullable: false),
                    FIFTHEENHARVYB = table.Column<float>(nullable: false),
                    FIFTHEENHARVBR = table.Column<float>(nullable: false),
                    FIFTHEENHARIR = table.Column<float>(nullable: false),
                    FIFTHEENHARIY = table.Column<float>(nullable: false),
                    FIFTHEENHARIB = table.Column<float>(nullable: false),
                    SIXTHEENHARVRY = table.Column<float>(nullable: false),
                    SIXTHEENHARVYB = table.Column<float>(nullable: false),
                    SIXTHEENHARVBR = table.Column<float>(nullable: false),
                    SIXTHEENHARIR = table.Column<float>(nullable: false),
                    SIXTHEENHARIY = table.Column<float>(nullable: false),
                    SIXTHEENHARIB = table.Column<float>(nullable: false),
                    SEVENTHEENHARVRY = table.Column<float>(nullable: false),
                    SEVENTHEENHARVYB = table.Column<float>(nullable: false),
                    SEVENTHEENHARVBR = table.Column<float>(nullable: false),
                    SEVENTHEENHARIR = table.Column<float>(nullable: false),
                    SEVENTHEENHARIY = table.Column<float>(nullable: false),
                    SEVENTHEENHARIB = table.Column<float>(nullable: false),
                    EIGHTHEENHARVRY = table.Column<float>(nullable: false),
                    EIGHTHEENHARVYB = table.Column<float>(nullable: false),
                    EIGHTHEENHARVBR = table.Column<float>(nullable: false),
                    EIGHTHEENHARIR = table.Column<float>(nullable: false),
                    EIGHTHEENHARIY = table.Column<float>(nullable: false),
                    EIGHTEENHARIB = table.Column<float>(nullable: false),
                    NINTHEENHARVRY = table.Column<float>(nullable: false),
                    NINTHEENHARVYB = table.Column<float>(nullable: false),
                    NINTHEENHARVBR = table.Column<float>(nullable: false),
                    NINTHEENHARIR = table.Column<float>(nullable: false),
                    NINTHEENHARIY = table.Column<float>(nullable: false),
                    NINTHEENHARIB = table.Column<float>(nullable: false),
                    TWENTYHARVRY = table.Column<float>(nullable: false),
                    TWENTYHARVYB = table.Column<float>(nullable: false),
                    TWENTYHARVBR = table.Column<float>(nullable: false),
                    TWENTYHARIR = table.Column<float>(nullable: false),
                    TWENTYHARIY = table.Column<float>(nullable: false),
                    TWENTYHARIB = table.Column<float>(nullable: false),
                    TWENTY1HARVRY = table.Column<float>(nullable: false),
                    TWENTY1HARVYB = table.Column<float>(nullable: false),
                    TWENTY1HARVBR = table.Column<float>(nullable: false),
                    TWENTY1HARIR = table.Column<float>(nullable: false),
                    TWENTY1HARIY = table.Column<float>(nullable: false),
                    TWENTY1HARIB = table.Column<float>(nullable: false),
                    TWENTY2HARVRY = table.Column<float>(nullable: false),
                    TWENTY2HARVYB = table.Column<float>(nullable: false),
                    TWENTY2HARVBR = table.Column<float>(nullable: false),
                    TWENTY2HARIR = table.Column<float>(nullable: false),
                    TWENTY2HARIY = table.Column<float>(nullable: false),
                    TWENTY2HARIB = table.Column<float>(nullable: false),
                    TWENTY3HARVRY = table.Column<float>(nullable: false),
                    TWENTY3HARVYB = table.Column<float>(nullable: false),
                    TWENTY3HARVBR = table.Column<float>(nullable: false),
                    TWENTY3HARIR = table.Column<float>(nullable: false),
                    TWENTY3HARIY = table.Column<float>(nullable: false),
                    TWENTY3HARIB = table.Column<float>(nullable: false),
                    TWENTY4HARVRY = table.Column<float>(nullable: false),
                    TWENTY4HARVYB = table.Column<float>(nullable: false),
                    TWENTY4HARVBR = table.Column<float>(nullable: false),
                    TWENTY4HARIR = table.Column<float>(nullable: false),
                    TWENTY4HARIY = table.Column<float>(nullable: false),
                    TWENTY4HARIB = table.Column<float>(nullable: false),
                    TWENTY5HARVRY = table.Column<float>(nullable: false),
                    TWENTY5HARVYB = table.Column<float>(nullable: false),
                    TWENTY5HARVBR = table.Column<float>(nullable: false),
                    TWENTY5HARIR = table.Column<float>(nullable: false),
                    TWENTY5HARIY = table.Column<float>(nullable: false),
                    TWENTY5HARIB = table.Column<float>(nullable: false),
                    TWENTY6HARVRY = table.Column<float>(nullable: false),
                    TWENTY6HARVYB = table.Column<float>(nullable: false),
                    TWENTY6HARVBR = table.Column<float>(nullable: false),
                    TWENTY6HARIR = table.Column<float>(nullable: false),
                    TWENTY6HARIY = table.Column<float>(nullable: false),
                    TWENTY6HARIB = table.Column<float>(nullable: false),
                    TWENTY7HARVRY = table.Column<float>(nullable: false),
                    TWENTY7HARVYB = table.Column<float>(nullable: false),
                    TWENTY7HARVBR = table.Column<float>(nullable: false),
                    TWENTY7HARIR = table.Column<float>(nullable: false),
                    TWENTY7HARIY = table.Column<float>(nullable: false),
                    TWENTY7HARIB = table.Column<float>(nullable: false),
                    TWENTY8HARVRY = table.Column<float>(nullable: false),
                    TWENTY8HARVYB = table.Column<float>(nullable: false),
                    TWENTY8HARVBR = table.Column<float>(nullable: false),
                    TWENTY8HARIR = table.Column<float>(nullable: false),
                    TWENTY8HARIY = table.Column<float>(nullable: false),
                    TWENTY8HARIB = table.Column<float>(nullable: false),
                    TWENTY9HARVRY = table.Column<float>(nullable: false),
                    TWENTY9HARVYB = table.Column<float>(nullable: false),
                    TWENTY9HARVBR = table.Column<float>(nullable: false),
                    TWENTY9HARIR = table.Column<float>(nullable: false),
                    TWENTY9HARIY = table.Column<float>(nullable: false),
                    TWENTY9HARIB = table.Column<float>(nullable: false),
                    THIRTYHARVRY = table.Column<float>(nullable: false),
                    THIRTYHARVYB = table.Column<float>(nullable: false),
                    THIRTYHARVBR = table.Column<float>(nullable: false),
                    THIRTYHARIR = table.Column<float>(nullable: false),
                    THIRTYHARIY = table.Column<float>(nullable: false),
                    THIRTYHARIB = table.Column<float>(nullable: false),
                    THIRTY1HARVRY = table.Column<float>(nullable: false),
                    THIRTY1HARVYB = table.Column<float>(nullable: false),
                    THIRTY1HARVBR = table.Column<float>(nullable: false),
                    THIRTY1HARIR = table.Column<float>(nullable: false),
                    THIRTY1HARIY = table.Column<float>(nullable: false),
                    THIRTY1HARIB = table.Column<float>(nullable: false),
                    THIRTY2HARVRY = table.Column<float>(nullable: false),
                    THIRTY2HARVYB = table.Column<float>(nullable: false),
                    THIRTY2HARVBR = table.Column<float>(nullable: false),
                    THIRTY2HARIR = table.Column<float>(nullable: false),
                    THIRTY2HARIY = table.Column<float>(nullable: false),
                    THIRTY2HARIB = table.Column<float>(nullable: false),
                    THIRTY3HARVRY = table.Column<float>(nullable: false),
                    THIRTY3HARVYB = table.Column<float>(nullable: false),
                    THIRTY3HARVBR = table.Column<float>(nullable: false),
                    THIRTY3HARIR = table.Column<float>(nullable: false),
                    THIRTY3HARIY = table.Column<float>(nullable: false),
                    THIRTY3HARIB = table.Column<float>(nullable: false),
                    ANALOGINPUT1 = table.Column<float>(nullable: false),
                    ANALOGINPUT2 = table.Column<float>(nullable: false),
                    ANALOGINPUT21 = table.Column<float>(nullable: false),
                    ANALOGINPUT3 = table.Column<float>(nullable: false),
                    ANALOGINPUT31 = table.Column<float>(nullable: false),
                    ANALOGINPUT4 = table.Column<float>(nullable: false),
                    ANALOGINPUT41 = table.Column<float>(nullable: false),
                    ANALOGINPUT5 = table.Column<float>(nullable: false),
                    ANALOGINPUT51 = table.Column<float>(nullable: false),
                    ANALOGINPUT6 = table.Column<float>(nullable: false),
                    ANALOGINPUT61 = table.Column<float>(nullable: false),
                    ANALOGINPUT7 = table.Column<float>(nullable: false),
                    ANALOGINPUT71 = table.Column<float>(nullable: false),
                    ANALOGINPUT8 = table.Column<float>(nullable: false),
                    ANALOGINPUT81 = table.Column<float>(nullable: false),
                    ANALOGINPUT9 = table.Column<float>(nullable: false),
                    ANALOGINPUT91 = table.Column<float>(nullable: false),
                    ANALOGINPUT10 = table.Column<float>(nullable: false),
                    ANALOGINPUT101 = table.Column<float>(nullable: false),
                    ANALOGINPUT11 = table.Column<float>(nullable: false),
                    ANALOGINPUT111 = table.Column<float>(nullable: false),
                    ANALOGINPUT12 = table.Column<float>(nullable: false),
                    DIGITALINPUT1 = table.Column<float>(nullable: false),
                    DIGITALINPUT2 = table.Column<float>(nullable: false),
                    DIGITALINPUT21 = table.Column<float>(nullable: false),
                    DIGITALINPUT3 = table.Column<float>(nullable: false),
                    DIGITALINPUT31 = table.Column<float>(nullable: false),
                    DIGITALINPUT4 = table.Column<float>(nullable: false),
                    DIGITALINPUT41 = table.Column<float>(nullable: false),
                    DIGITALINPUT5 = table.Column<float>(nullable: false),
                    DIGITALINPUT51 = table.Column<float>(nullable: false),
                    DIGITALINPUT6 = table.Column<float>(nullable: false),
                    DIGITALINPUT61 = table.Column<float>(nullable: false),
                    DIGITALINPUT7 = table.Column<float>(nullable: false),
                    DIGITALINPUT71 = table.Column<float>(nullable: false),
                    DIGITALINPUT8 = table.Column<float>(nullable: false),
                    DIGITALINPUT81 = table.Column<float>(nullable: false),
                    DIGITALINPUT9 = table.Column<float>(nullable: false),
                    DIGITALINPUT91 = table.Column<float>(nullable: false),
                    DIGITALINPUT10 = table.Column<float>(nullable: false),
                    DIGITALINPUT101 = table.Column<float>(nullable: false),
                    DIGITALINPUT11 = table.Column<float>(nullable: false),
                    DIGITALINPUT111 = table.Column<float>(nullable: false),
                    DIGITALINPUT12 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT1 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT2 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT21 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT3 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT31 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT4 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT41 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT5 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT51 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT6 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT61 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT7 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT71 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT8 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT81 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT9 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT91 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT10 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT101 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT11 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT111 = table.Column<float>(nullable: false),
                    DIGITALOUTPUT12 = table.Column<float>(nullable: false),
                    PULSEOUTPUT1 = table.Column<float>(nullable: false),
                    PULSEOUTPUT2 = table.Column<float>(nullable: false),
                    PULSEOUTPUT3 = table.Column<float>(nullable: false),
                    PULSEOUTPUT4 = table.Column<float>(nullable: false),
                    PULSEOUTPUT5 = table.Column<float>(nullable: false),
                    PULSEOUTPUT6 = table.Column<float>(nullable: false),
                    ABTBLOCK1 = table.Column<float>(nullable: false),
                    ABTBLOCK2 = table.Column<float>(nullable: false),
                    ABTBLOCK3 = table.Column<float>(nullable: false),
                    ABTBLOCK4 = table.Column<float>(nullable: false),
                    ABTBLOCK5 = table.Column<float>(nullable: false),
                    ABTBLOCK6 = table.Column<float>(nullable: false),
                    ABTBLOCK7 = table.Column<float>(nullable: false),
                    ABTBLOCK8 = table.Column<float>(nullable: false),
                    ABTBLOCK9 = table.Column<float>(nullable: false),
                    ABTBLOCK10 = table.Column<float>(nullable: false),
                    ABTBLOCK11 = table.Column<float>(nullable: false),
                    ABTBLOCK12 = table.Column<float>(nullable: false),
                    ABTBLOCK13 = table.Column<float>(nullable: false),
                    ABTBLOCK14 = table.Column<float>(nullable: false),
                    ABTBLOCK15 = table.Column<float>(nullable: false),
                    ABTBLOCK16 = table.Column<float>(nullable: false),
                    ABTBLOCK17 = table.Column<float>(nullable: false),
                    ABTBLOCK18 = table.Column<float>(nullable: false),
                    ABTBLOCK19 = table.Column<float>(nullable: false),
                    ABTBLOCK20 = table.Column<float>(nullable: false),
                    ABTBLOCK21 = table.Column<float>(nullable: false),
                    ABTBLOCK22 = table.Column<float>(nullable: false),
                    ABTBLOCK23 = table.Column<float>(nullable: false),
                    ABTBLOCK24 = table.Column<float>(nullable: false),
                    ABTBLOCK25 = table.Column<float>(nullable: false),
                    ABTBLOCK26 = table.Column<float>(nullable: false),
                    ABTBLOCK27 = table.Column<float>(nullable: false),
                    ABTBLOCK28 = table.Column<float>(nullable: false),
                    ABTBLOCK29 = table.Column<float>(nullable: false),
                    ABTBLOCK30 = table.Column<float>(nullable: false),
                    ABTBLOCK31 = table.Column<float>(nullable: false),
                    ABTBLOCK32 = table.Column<float>(nullable: false),
                    ABTBLOCK33 = table.Column<float>(nullable: false),
                    ABTBLOCK34 = table.Column<float>(nullable: false),
                    ABTBLOCK35 = table.Column<float>(nullable: false),
                    ABTBLOCK36 = table.Column<float>(nullable: false),
                    ABTBLOCK37 = table.Column<float>(nullable: false),
                    ABTBLOCK38 = table.Column<float>(nullable: false),
                    ABTBLOCK39 = table.Column<float>(nullable: false),
                    ABTBLOCK40 = table.Column<float>(nullable: false),
                    ABTBLOCK41 = table.Column<float>(nullable: false),
                    ABTBLOCK42 = table.Column<float>(nullable: false),
                    ABTBLOCK43 = table.Column<float>(nullable: false),
                    ABTBLOCK44 = table.Column<float>(nullable: false),
                    ABTBLOCK45 = table.Column<float>(nullable: false),
                    ABTBLOCK46 = table.Column<float>(nullable: false),
                    ABTBLOCK47 = table.Column<float>(nullable: false),
                    ABTBLOCK48 = table.Column<float>(nullable: false),
                    ABTBLOCK49 = table.Column<float>(nullable: false),
                    ABTBLOCK50 = table.Column<float>(nullable: false),
                    ABTBLOCK51 = table.Column<float>(nullable: false),
                    ABTBLOCK52 = table.Column<float>(nullable: false),
                    ABTBLOCK53 = table.Column<float>(nullable: false),
                    ABTBLOCK54 = table.Column<float>(nullable: false),
                    ABTBLOCK55 = table.Column<float>(nullable: false),
                    ABTBLOCK56 = table.Column<float>(nullable: false),
                    ABTBLOCK57 = table.Column<float>(nullable: false),
                    ABTBLOCK58 = table.Column<float>(nullable: false),
                    ABTBLOCK59 = table.Column<float>(nullable: false),
                    ABTBLOCK60 = table.Column<float>(nullable: false),
                    ABTBLOCK61 = table.Column<float>(nullable: false),
                    ABTBLOCK62 = table.Column<float>(nullable: false),
                    ABTBLOCK63 = table.Column<float>(nullable: false),
                    ABTBLOCK64 = table.Column<float>(nullable: false),
                    ABTBLOCK65 = table.Column<float>(nullable: false),
                    ABTBLOCK66 = table.Column<float>(nullable: false),
                    ABTBLOCK67 = table.Column<float>(nullable: false),
                    ABTBLOCK68 = table.Column<float>(nullable: false),
                    ABTBLOCK69 = table.Column<float>(nullable: false),
                    ABTBLOCK70 = table.Column<float>(nullable: false),
                    ABTBLOCK71 = table.Column<float>(nullable: false),
                    ABTBLOCK72 = table.Column<float>(nullable: false),
                    ABTBLOCK73 = table.Column<float>(nullable: false),
                    ABTBLOCK74 = table.Column<float>(nullable: false),
                    ABTBLOCK75 = table.Column<float>(nullable: false),
                    ABTBLOCK76 = table.Column<float>(nullable: false),
                    ABTBLOCK77 = table.Column<float>(nullable: false),
                    ABTBLOCK78 = table.Column<float>(nullable: false),
                    ABTBLOCK79 = table.Column<float>(nullable: false),
                    ABTBLOCK80 = table.Column<float>(nullable: false),
                    ABTBLOCK81 = table.Column<float>(nullable: false),
                    ABTBLOCK82 = table.Column<float>(nullable: false),
                    ABTBLOCK83 = table.Column<float>(nullable: false),
                    ABTBLOCK84 = table.Column<float>(nullable: false),
                    ABTBLOCK85 = table.Column<float>(nullable: false),
                    ABTBLOCK86 = table.Column<float>(nullable: false),
                    ABTBLOCK87 = table.Column<float>(nullable: false),
                    ABTBLOCK88 = table.Column<float>(nullable: false),
                    ABTBLOCK89 = table.Column<float>(nullable: false),
                    ABTBLOCK90 = table.Column<float>(nullable: false),
                    ABTBLOCK91 = table.Column<float>(nullable: false),
                    ABTBLOCK92 = table.Column<float>(nullable: false),
                    ABTBLOCK93 = table.Column<float>(nullable: false),
                    ABTBLOCK94 = table.Column<float>(nullable: false),
                    ABTBLOCK95 = table.Column<float>(nullable: false),
                    ABTBLOCK96 = table.Column<float>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_emsMaster", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "PM520L",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    StartDate = table.Column<DateTime>(nullable: false),
                    EndDate = table.Column<DateTime>(nullable: false),
                    ModBusAddress = table.Column<int>(nullable: false),
                    Parameter = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PM520L", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "priviliges",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    StartDate = table.Column<DateTime>(nullable: false),
                    EndDate = table.Column<DateTime>(nullable: false),
                    PrivilegeName = table.Column<string>(nullable: true),
                    CustomerId = table.Column<int>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_priviliges", x => x.Id);
                    table.ForeignKey(
                        name: "FK_priviliges_customers_CustomerId",
                        column: x => x.CustomerId,
                        principalTable: "customers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "customerpriviliges",
                columns: table => new
                {
                    CustomerId = table.Column<int>(nullable: false),
                    PrivilegeId = table.Column<int>(nullable: false),
                    PriviligesId = table.Column<int>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_customerpriviliges", x => new { x.CustomerId, x.PrivilegeId });
                    table.ForeignKey(
                        name: "FK_customerpriviliges_customers_CustomerId",
                        column: x => x.CustomerId,
                        principalTable: "customers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_customerpriviliges_priviliges_PriviligesId",
                        column: x => x.PriviligesId,
                        principalTable: "priviliges",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_customerpriviliges_PriviligesId",
                table: "customerpriviliges",
                column: "PriviligesId");

            migrationBuilder.CreateIndex(
                name: "IX_priviliges_CustomerId",
                table: "priviliges",
                column: "CustomerId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "customerpriviliges");

            migrationBuilder.DropTable(
                name: "emsMaster");

            migrationBuilder.DropTable(
                name: "PM520L");

            migrationBuilder.DropTable(
                name: "priviliges");

            migrationBuilder.DropTable(
                name: "customers");
        }
    }
}
