// <auto-generated />
using System;
using EMS.ModelBuilderRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EMS.ModelBuilderRepository.Migrations
{
    [DbContext(typeof(EmsModelContext))]
    [Migration("20200415101924_Add_Entire_Table")]
    partial class Add_Entire_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EMS.ModelBuilderRepository.Models.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlockName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModBusFC")
                        .HasColumnType("int");

                    b.Property<int>("StartAddress")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalParams")
                        .HasColumnType("int");

                    b.Property<int>("TotalReg")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Block");
                });

            modelBuilder.Entity("EMS.ModelBuilderRepository.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContatctPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Controlling")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DG")
                        .HasColumnType("int");

                    b.Property<int>("Demand")
                        .HasColumnType("int");

                    b.Property<int>("DemandCharges")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSTNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Incomers")
                        .HasColumnType("int");

                    b.Property<DateTime>("LicenceExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Monitoring")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfMachine")
                        .HasColumnType("int");

                    b.Property<int>("NoOfPlants")
                        .HasColumnType("int");

                    b.Property<int>("NoOfTransformers")
                        .HasColumnType("int");

                    b.Property<string>("PAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PenaltyCharges")
                        .HasColumnType("int");

                    b.Property<string>("PlantAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RRNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialMedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Solar")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Transformer1Rating")
                        .HasColumnType("int");

                    b.Property<int>("Transformer2Rating")
                        .HasColumnType("int");

                    b.Property<int>("Transformer3Rating")
                        .HasColumnType("int");

                    b.Property<int>("Transformer4Rating")
                        .HasColumnType("int");

                    b.Property<int>("Transformer5Rating")
                        .HasColumnType("int");

                    b.Property<string>("UAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("EMS.ModelBuilderRepository.Models.CustomerPriviliges", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("int");

                    b.Property<int?>("PriviligesId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "PrivilegeId");

                    b.HasIndex("PriviligesId");

                    b.ToTable("customerpriviliges");
                });

            modelBuilder.Entity("EMS.ModelBuilderRepository.Models.EmsMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("ABTBLOCK1")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK10")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK11")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK12")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK13")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK14")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK15")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK16")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK17")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK18")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK19")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK2")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK20")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK21")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK22")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK23")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK24")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK25")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK26")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK27")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK28")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK29")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK3")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK30")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK31")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK32")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK33")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK34")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK35")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK36")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK37")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK38")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK39")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK4")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK40")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK41")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK42")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK43")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK44")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK45")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK46")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK47")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK48")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK49")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK5")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK50")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK51")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK52")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK53")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK54")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK55")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK56")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK57")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK58")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK59")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK6")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK60")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK61")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK62")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK63")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK64")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK65")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK66")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK67")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK68")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK69")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK7")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK70")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK71")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK72")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK73")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK74")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK75")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK76")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK77")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK78")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK79")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK8")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK80")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK81")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK82")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK83")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK84")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK85")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK86")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK87")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK88")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK89")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK9")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK90")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK91")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK92")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK93")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK94")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK95")
                        .HasColumnType("real");

                    b.Property<float>("ABTBLOCK96")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT1")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT10")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT101")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT11")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT111")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT12")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT2")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT21")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT3")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT31")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT4")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT41")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT5")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT51")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT6")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT61")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT7")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT71")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT8")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT81")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT9")
                        .HasColumnType("real");

                    b.Property<float>("ANALOGINPUT91")
                        .HasColumnType("real");

                    b.Property<float>("DEMAND1")
                        .HasColumnType("real");

                    b.Property<float>("DEMAND2")
                        .HasColumnType("real");

                    b.Property<float>("DEMAND3")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT1")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT10")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT101")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT11")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT111")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT12")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT2")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT21")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT3")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT31")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT4")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT41")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT5")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT51")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT6")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT61")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT7")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT71")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT8")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT81")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT9")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALINPUT91")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT1")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT10")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT101")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT11")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT111")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT12")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT2")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT21")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT3")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT31")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT4")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT41")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT5")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT51")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT6")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT61")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT7")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT71")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT8")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT81")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT9")
                        .HasColumnType("real");

                    b.Property<float>("DIGITALOUTPUT91")
                        .HasColumnType("real");

                    b.Property<int>("DataPort")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEms")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<float>("EIGHTEENHARIB")
                        .HasColumnType("real");

                    b.Property<float>("EIGHTHARIB")
                        .HasColumnType("real");

                    b.Property<float>("EIGHTHARIR")
                        .HasColumnType("real");

                    b.Property<float>("EIGHTHARIY")
                        .HasColumnType("real");

                    b.Property<float>("EIGHTHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("EIGHTHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("EIGHTHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("EIGHTHEENHARIR")
                        .HasColumnType("real");

                    b.Property<float>("EIGHTHEENHARIY")
                        .HasColumnType("real");

                    b.Property<float>("EIGHTHEENHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("EIGHTHEENHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("EIGHTHEENHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("ELEVENTHHARIB")
                        .HasColumnType("real");

                    b.Property<float>("ELEVENTHHARIR")
                        .HasColumnType("real");

                    b.Property<float>("ELEVENTHHARIY")
                        .HasColumnType("real");

                    b.Property<float>("ELEVENTHHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("ELEVENTHHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("ELEVENTHHARVYB")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("FIFTHEENHARIB")
                        .HasColumnType("real");

                    b.Property<float>("FIFTHEENHARIR")
                        .HasColumnType("real");

                    b.Property<float>("FIFTHEENHARIY")
                        .HasColumnType("real");

                    b.Property<float>("FIFTHEENHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("FIFTHEENHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("FIFTHEENHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("FIFTHHARIB")
                        .HasColumnType("real");

                    b.Property<float>("FIFTHHARIR")
                        .HasColumnType("real");

                    b.Property<float>("FIFTHHARIY")
                        .HasColumnType("real");

                    b.Property<float>("FIFTHHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("FIFTHHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("FIFTHHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("FIRSTSTHRIB")
                        .HasColumnType("real");

                    b.Property<float>("FIRSTSTHRIR")
                        .HasColumnType("real");

                    b.Property<float>("FIRSTSTHRIY")
                        .HasColumnType("real");

                    b.Property<float>("FIRSTSTHRVBR")
                        .HasColumnType("real");

                    b.Property<float>("FIRSTSTHRVRY")
                        .HasColumnType("real");

                    b.Property<float>("FIRSTSTHRVYB")
                        .HasColumnType("real");

                    b.Property<float>("FOURTEENHARIB")
                        .HasColumnType("real");

                    b.Property<float>("FOURTEENHARIR")
                        .HasColumnType("real");

                    b.Property<float>("FOURTEENHARIY")
                        .HasColumnType("real");

                    b.Property<float>("FOURTEENHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("FOURTEENHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("FOURTEENHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("FOURTHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("FOURTHHARIB")
                        .HasColumnType("real");

                    b.Property<float>("FOURTHHARIR")
                        .HasColumnType("real");

                    b.Property<float>("FOURTHHARIY")
                        .HasColumnType("real");

                    b.Property<float>("FOURTHHARVRY")
                        .HasColumnType("real");

                    b.Property<int>("FunctionCode")
                        .HasColumnType("int");

                    b.Property<float>("HZ")
                        .HasColumnType("real");

                    b.Property<float>("IAVG")
                        .HasColumnType("real");

                    b.Property<float>("IB")
                        .HasColumnType("real");

                    b.Property<float>("IR")
                        .HasColumnType("real");

                    b.Property<float>("IY")
                        .HasColumnType("real");

                    b.Property<float>("MAXIMAMDEMAND")
                        .HasColumnType("real");

                    b.Property<float>("NEUTRALCURRENTLN")
                        .HasColumnType("real");

                    b.Property<float>("NINTHEENHARIB")
                        .HasColumnType("real");

                    b.Property<float>("NINTHEENHARIR")
                        .HasColumnType("real");

                    b.Property<float>("NINTHEENHARIY")
                        .HasColumnType("real");

                    b.Property<float>("NINTHEENHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("NINTHEENHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("NINTHEENHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("NINTHHARIB")
                        .HasColumnType("real");

                    b.Property<float>("NINTHHARIR")
                        .HasColumnType("real");

                    b.Property<float>("NINTHHARIY")
                        .HasColumnType("real");

                    b.Property<float>("NINTHHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("NINTHHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("NINTHHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("PFAVG")
                        .HasColumnType("real");

                    b.Property<float>("PFB")
                        .HasColumnType("real");

                    b.Property<float>("PFR")
                        .HasColumnType("real");

                    b.Property<float>("PFY")
                        .HasColumnType("real");

                    b.Property<float>("PULSEOUTPUT1")
                        .HasColumnType("real");

                    b.Property<float>("PULSEOUTPUT2")
                        .HasColumnType("real");

                    b.Property<float>("PULSEOUTPUT3")
                        .HasColumnType("real");

                    b.Property<float>("PULSEOUTPUT4")
                        .HasColumnType("real");

                    b.Property<float>("PULSEOUTPUT5")
                        .HasColumnType("real");

                    b.Property<float>("PULSEOUTPUT6")
                        .HasColumnType("real");

                    b.Property<float>("RISINGDEMAND")
                        .HasColumnType("real");

                    b.Property<float>("RPM")
                        .HasColumnType("real");

                    b.Property<float>("SECONDHARIB")
                        .HasColumnType("real");

                    b.Property<float>("SECONDHARIR")
                        .HasColumnType("real");

                    b.Property<float>("SECONDHARIY")
                        .HasColumnType("real");

                    b.Property<float>("SECONDHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("SECONDHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("SECONDHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("SEVENTHEENHARIB")
                        .HasColumnType("real");

                    b.Property<float>("SEVENTHEENHARIR")
                        .HasColumnType("real");

                    b.Property<float>("SEVENTHEENHARIY")
                        .HasColumnType("real");

                    b.Property<float>("SEVENTHEENHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("SEVENTHEENHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("SEVENTHEENHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("SEVENTHHARIB")
                        .HasColumnType("real");

                    b.Property<float>("SEVENTHHARIR")
                        .HasColumnType("real");

                    b.Property<float>("SEVENTHHARIY")
                        .HasColumnType("real");

                    b.Property<float>("SEVENTHHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("SEVENTHHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("SEVENTHHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("SIXTHEENHARIB")
                        .HasColumnType("real");

                    b.Property<float>("SIXTHEENHARIR")
                        .HasColumnType("real");

                    b.Property<float>("SIXTHEENHARIY")
                        .HasColumnType("real");

                    b.Property<float>("SIXTHEENHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("SIXTHEENHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("SIXTHEENHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("SIXTHHARIB")
                        .HasColumnType("real");

                    b.Property<float>("SIXTHHARIR")
                        .HasColumnType("real");

                    b.Property<float>("SIXTHHARIY")
                        .HasColumnType("real");

                    b.Property<float>("SIXTHHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("SIXTHHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("SIXTHHARVYB")
                        .HasColumnType("real");

                    b.Property<int>("SlaveId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartingAddress")
                        .HasColumnType("int");

                    b.Property<float>("TENTHHARIB")
                        .HasColumnType("real");

                    b.Property<float>("TENTHHARIR")
                        .HasColumnType("real");

                    b.Property<float>("TENTHHARIY")
                        .HasColumnType("real");

                    b.Property<float>("TENTHHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("TENTHHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("TENTHHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("THDCURRENTA")
                        .HasColumnType("real");

                    b.Property<float>("THDVOLTAGEVLL")
                        .HasColumnType("real");

                    b.Property<float>("THDVOLTAGEVLN")
                        .HasColumnType("real");

                    b.Property<float>("THIRDDHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("THIRDHARIB")
                        .HasColumnType("real");

                    b.Property<float>("THIRDHARIR")
                        .HasColumnType("real");

                    b.Property<float>("THIRDHARIY")
                        .HasColumnType("real");

                    b.Property<float>("THIRDHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("THIRDHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("THIRDHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("THIRTEENHARIB")
                        .HasColumnType("real");

                    b.Property<float>("THIRTEENHARIR")
                        .HasColumnType("real");

                    b.Property<float>("THIRTEENHARIY")
                        .HasColumnType("real");

                    b.Property<float>("THIRTEENHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("THIRTEENHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("THIRTEENHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY1HARIB")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY1HARIR")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY1HARIY")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY1HARVBR")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY1HARVRY")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY1HARVYB")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY2HARIB")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY2HARIR")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY2HARIY")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY2HARVBR")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY2HARVRY")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY2HARVYB")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY3HARIB")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY3HARIR")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY3HARIY")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY3HARVBR")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY3HARVRY")
                        .HasColumnType("real");

                    b.Property<float>("THIRTY3HARVYB")
                        .HasColumnType("real");

                    b.Property<float>("THIRTYHARIB")
                        .HasColumnType("real");

                    b.Property<float>("THIRTYHARIR")
                        .HasColumnType("real");

                    b.Property<float>("THIRTYHARIY")
                        .HasColumnType("real");

                    b.Property<float>("THIRTYHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("THIRTYHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("THIRTYHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("TWELVEHARIB")
                        .HasColumnType("real");

                    b.Property<float>("TWELVEHARIR")
                        .HasColumnType("real");

                    b.Property<float>("TWELVEHARIY")
                        .HasColumnType("real");

                    b.Property<float>("TWELVEHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("TWELVEHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("TWELVEHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY1HARIB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY1HARIR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY1HARIY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY1HARVBR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY1HARVRY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY1HARVYB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY2HARIB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY2HARIR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY2HARIY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY2HARVBR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY2HARVRY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY2HARVYB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY3HARIB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY3HARIR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY3HARIY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY3HARVBR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY3HARVRY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY3HARVYB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY4HARIB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY4HARIR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY4HARIY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY4HARVBR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY4HARVRY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY4HARVYB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY5HARIB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY5HARIR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY5HARIY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY5HARVBR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY5HARVRY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY5HARVYB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY6HARIB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY6HARIR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY6HARIY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY6HARVBR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY6HARVRY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY6HARVYB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY7HARIB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY7HARIR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY7HARIY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY7HARVBR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY7HARVRY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY7HARVYB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY8HARIB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY8HARIR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY8HARIY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY8HARVBR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY8HARVRY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY8HARVYB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY9HARIB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY9HARIR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY9HARIY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY9HARVBR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY9HARVRY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTY9HARVYB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTYHARIB")
                        .HasColumnType("real");

                    b.Property<float>("TWENTYHARIR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTYHARIY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTYHARVBR")
                        .HasColumnType("real");

                    b.Property<float>("TWENTYHARVRY")
                        .HasColumnType("real");

                    b.Property<float>("TWENTYHARVYB")
                        .HasColumnType("real");

                    b.Property<float>("UNBALANCECURRENTAMPS")
                        .HasColumnType("real");

                    b.Property<float>("UNBALANCEVOLTAGEVLL")
                        .HasColumnType("real");

                    b.Property<float>("UNBALANCEVOLTAGEVLN")
                        .HasColumnType("real");

                    b.Property<float>("VAB")
                        .HasColumnType("real");

                    b.Property<float>("VAHCB")
                        .HasColumnType("real");

                    b.Property<float>("VAHCONTOT")
                        .HasColumnType("real");

                    b.Property<float>("VAHCR")
                        .HasColumnType("real");

                    b.Property<float>("VAHCY")
                        .HasColumnType("real");

                    b.Property<float>("VAHGB")
                        .HasColumnType("real");

                    b.Property<float>("VAHGENTOT")
                        .HasColumnType("real");

                    b.Property<float>("VAHGR")
                        .HasColumnType("real");

                    b.Property<float>("VAHGY")
                        .HasColumnType("real");

                    b.Property<float>("VAR")
                        .HasColumnType("real");

                    b.Property<float>("VARB")
                        .HasColumnType("real");

                    b.Property<float>("VARHB")
                        .HasColumnType("real");

                    b.Property<float>("VARHCAPB")
                        .HasColumnType("real");

                    b.Property<float>("VARHCAPR")
                        .HasColumnType("real");

                    b.Property<float>("VARHCAPT")
                        .HasColumnType("real");

                    b.Property<float>("VARHCAPY")
                        .HasColumnType("real");

                    b.Property<float>("VARHINDB")
                        .HasColumnType("real");

                    b.Property<float>("VARHINDR")
                        .HasColumnType("real");

                    b.Property<float>("VARHINDT")
                        .HasColumnType("real");

                    b.Property<float>("VARHINDY")
                        .HasColumnType("real");

                    b.Property<float>("VARHR")
                        .HasColumnType("real");

                    b.Property<float>("VARHTOT")
                        .HasColumnType("real");

                    b.Property<float>("VARHY")
                        .HasColumnType("real");

                    b.Property<float>("VARR")
                        .HasColumnType("real");

                    b.Property<float>("VARTOT")
                        .HasColumnType("real");

                    b.Property<float>("VARY")
                        .HasColumnType("real");

                    b.Property<float>("VATOT")
                        .HasColumnType("real");

                    b.Property<float>("VAY")
                        .HasColumnType("real");

                    b.Property<float>("VB")
                        .HasColumnType("real");

                    b.Property<float>("VBR")
                        .HasColumnType("real");

                    b.Property<float>("VLLAVG")
                        .HasColumnType("real");

                    b.Property<float>("VLNAVG")
                        .HasColumnType("real");

                    b.Property<float>("VR")
                        .HasColumnType("real");

                    b.Property<float>("VRY")
                        .HasColumnType("real");

                    b.Property<float>("VY")
                        .HasColumnType("real");

                    b.Property<float>("VYB")
                        .HasColumnType("real");

                    b.Property<float>("WB")
                        .HasColumnType("real");

                    b.Property<float>("WHCB")
                        .HasColumnType("real");

                    b.Property<float>("WHCONTOT")
                        .HasColumnType("real");

                    b.Property<float>("WHCR")
                        .HasColumnType("real");

                    b.Property<float>("WHCY")
                        .HasColumnType("real");

                    b.Property<float>("WHGB")
                        .HasColumnType("real");

                    b.Property<float>("WHGENTOT")
                        .HasColumnType("real");

                    b.Property<float>("WHGR")
                        .HasColumnType("real");

                    b.Property<float>("WHGY")
                        .HasColumnType("real");

                    b.Property<float>("WR")
                        .HasColumnType("real");

                    b.Property<float>("WY")
                        .HasColumnType("real");

                    b.Property<float>("WattsTot")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("emsMaster");
                });

            modelBuilder.Entity("EMS.ModelBuilderRepository.Models.PM520L", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModBusAddress")
                        .HasColumnType("int");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PM520L");
                });

            modelBuilder.Entity("EMS.ModelBuilderRepository.Models.Priviliges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrivilegeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("priviliges");
                });

            modelBuilder.Entity("EMS.ModelBuilderRepository.Models.CustomerPriviliges", b =>
                {
                    b.HasOne("EMS.ModelBuilderRepository.Models.Customer", "Customers")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.ModelBuilderRepository.Models.Priviliges", "Priviliges")
                        .WithMany()
                        .HasForeignKey("PriviligesId");
                });

            modelBuilder.Entity("EMS.ModelBuilderRepository.Models.Priviliges", b =>
                {
                    b.HasOne("EMS.ModelBuilderRepository.Models.Customer", "Customer")
                        .WithMany("Priviliges")
                        .HasForeignKey("CustomerId");
                });
#pragma warning restore 612, 618
        }
    }
}
